on:
  push:
    branches:
      - main
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: Bumping version
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: "packages/vscode-scripts"
        with:
          version-type: "patch"
          tag-prefix: "v"
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN --no-dependencies"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
